import React from "react"
import Link from 'next/link'
import Image from 'next/image'
import Logo from '../public/static/assets/img/logo.webp'

export default function ProductModal() {
	const myArray = [
		{'name':'Unpolished Urad Whole','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0000_DeHaat_FOP_Unpolished_Urad_Whole_1kg_260722.webp','content':'Whole Urad Dal is rich in proteins, potassium calcium and iron. It is healthy and delicious with a great and wholesome taste. It is rich source of nutrients like potassium, calcium, and B-vitamins to keep you healthy.<br/>Our Whole Urad Dal is unpolished and is pesticide-free. What’s more, it can be traced to its source of origin.<br/><br/>This one comes to you from Virudhnagar in Tamil Nadu. Be sure to get your White Whole Urad from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Whole Urad Dal is available in 500gms and 1kg packs.</strong>'},
		{'name':'Unpolished Urad Kali','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0001_DeHaat_FOP_Unpolished_Urad_Kali_1kg_260722.webp','content':'This simple lentil is full of iron, folic acid, calcium, magnesium, and potassium. It is delicious and is used to make a whole range of dishes.<br/><br/>Our Black Urad Dal is unpolished, pesticide-free and can be traced to its source of origin.<br/><br/>This pack comes to you from Guna and Narsinghpur districts of Madhya Pradesh. Be sure to get your Unpolished Black Urad Dal from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Kali Urad Dal is available in 500gms and 1kg packs.</strong>'},
		{'name':'Unpolished Urad Dal','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0002_DeHaat_FOP_Unpolished_Urad_Dal_1kg_260722.webp','content':'Urad Dal is one of the richest sources of proteins and vitamins. it is a rich source of protein for the body. It contains essential minerals like potassium, iron, magnesium, and phosphorous. Commonly used in cooking a variety of dishes like dishes like idlis, papad, vadas, dosas etc., our Urad Dal is processed from premium-quality grains for a great and wholesome taste. <br/><br/>Our Urad Dal is unpolished, pesticide-free and can be traced to its source of origin.<br/><br/>This one comes to you from Virudhnagar in Tamil Nadu. Be sure to get your Urad Dal from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Urad Dal is available in 500gms and 1kg packs.</strong>'},
		{'name':'Unpolished Urad Chilka','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0003_DeHaat_FOP_Unpolished_Urad_Chilka_1kg_260722.webp','content':'Urad Chilka is a rich source of antioxidants and fibre content. It is rich in protein, B complex vitamins, and minerals like iron and manganese.<br/><br/>Our Urad Chilka Dal is unpolished and comes with a pesticide-free guarantee. It can even be traced to its source of origin.<br/><br/>This pack comes to you from Guna and Narsinghpur districts of Madhya Pradesh. Be sure to get your Unpolished Urad Chilka Dal from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Urad Chilka Dal is available in 500gms and 1kg packs.</strong>'},
		{'name':'Unpolished Toor Dal (Arhar Dal)','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0004_DeHaat_FOP_Unpolished_Toor_Dal_1kg_260722.webp','content':'Our Toor Dal is protein-rich, and has no cholesterol, additives, or impurities. This dal is unpolished and is guaranteed pesticide-free. What’s more, it is even traceable to its source of origin.<br/><br/>This one comes to you from one of the most prominent Toor Dal growing regions of Gulbarga in Karnataka, along with Akola in Maharashtra & Mandla in Madhya Pradesh. Be sure to get your Unpolished Toor Dal from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Toor Dal (Arhar Dal) is available in 500gms and 1kg packs.</strong>'},
		{'name':'Unpolished Rajma (Kashmiri)','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0005_DeHaat_FOP_Unpolished_Rajma_Kashmiri_1kg_260722.webp','content':'A traditional delicacy, our Unpolished Kashmiri Rajma is loaded with nutrients. It helps build muscles and in tissue repair thanks to its high protein content. It is rich in vitamins and minerals.<br/><br/>Kashmiri Rajma is also high in nutrients like copper, iron, manganese, phosphorus, molybdenum, vitamin B1 and folate.<br/><br/>Our Kashmiri Rajma is unpolished and pesticide-free. It can even be traced to its source of origin.<br/><br/>Be sure to get your Unpolished Kashmiri Rajma from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Rajma (Kashmiri) is available in 500gms and 1kg packs.</strong>'},
		{'name':'Raw Peanuts','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0015_DeHaat_FOP_Raw_Peanuts_1kg_260722.webp','content':'Peanuts are a high-protein, nutrient-rich snack. Our raw peanuts have no preservatives, are natural, non-GMO and guaranteed pesticide-free. What’s more, they are even traceable to their source of origin. <br/><br/>This lot comes to you from Anantpur, Andhra Pradesh. Be sure to get your Raw Peanuts from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Raw Peanuts are available in 500gms and 1kg packs.</strong>'},
		{'name':'Unpolished Chana Dal','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0012_DeHaat_FOP_Unpolished_Chana_Dal_1kg_260722.webp','content':'Chana Dal is rich in proteins, antioxidants, and methionine amino acid. It is also high in B-complex vitamins. It has low starch and high fibre content. This makes it very healthy to eat.<br/><br/>Our Chana Dal is unpolished and comes with a pesticide-free guarantee. What’s more, it can be traced to its source of origin.<br/><br/>This one comes to you from Mandla in Madhya Pradesh. Be sure to get your Unpolished Chana Dal from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Chana Dal is available in 500gms and 1kg packs.</strong>'},
		{'name':'Premium Basmati Rice','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0014_DeHaat_FOP_Rozana_Basmati_Rice_1kg_260722.webp','content':'Our Premium Basmati Rice is above medium length product. The rice is guaranteed pesticide-free and is traceable to its source of origin.<br/>This one comes to you from Karnal, Haryana.<br/><br/>It is specially processed for daily cooking across a multitude of regular dishes, a perfect fit for everyday consumption. Be sure to get your Premium Basmati Rice from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Premium Basmati Rice is available in 1kg and 5kg packs.</strong>'},
		{'name':'Sona Masuri Rice White','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0013_DeHaat_FOP_Sona_Masuri_Rice_White_1kg_260722.webp','content':'Sona Masuri Rice is rich in nutrient content and easy to digest. This tasty variety of rice is light in weight with a medium-sized grain characterised by distinctive taste and aroma. The non-sticky nature of this rice is its key feature.<br/><br/>Our Sona Masuri Rice is pesticide-free and can be traced to its source of origin.<br/><br/>This one comes to you from the nutrient rich lands of Raichur in Karnataka. Be sure to get your Sona Masuri Rice from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Sona Masuri Rice is available in 1kg packs.</strong>'},
		{'name':'Unpolished Green Moong','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0011_DeHaat_FOP_Unpolished_Green_Moong_1kg_260722.webp','content':'Green Moong is a nutrient-rich food with high protein content. It is enriched with minerals like potassium, magnesium, iron, and copper. It also contains folate, fibre, and vitamin B6.<br/><br/>Our Green Moong is unpolished, pesticide-free and is traceable to its source of origin.<br/><br/>This pack comes to you from Surat and Bharuch in Gujarat. Be sure to get your Unpolished Green Moong from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Green Moong is available in 500gms and 1kg packs.</strong>'},
		{'name':'Unpolished Rajma (Chitra)','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0006_DeHaat_FOP_Unpolished_Rajma_Chitra_1kg_260722.webp','content':'Chitra Rajma is a very good source of natural detoxifiers, minerals, vitamins B3 and B6, manganese and calcium.<br/><br/>Our Chitra Rajma is unpolished, pesticide-free and is traceable to its source of origin.<br/><br/>This one comes to you from the Satara district of Maharashtra. Be sure to get your Unpolished Chitra Rajma from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Rajma (Chitra) is available in 500gms and 1kg packs.</strong>'},
		{'name':'Unpolished Moong Dal Chilka','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0007_DeHaat_FOP_Unpolished_Moong_Dal_Chilka_1kg_260722.webp','content':'Moong Chilka is very rich in protein, resistant starch, and dietary fibre. It also has high levels of B vitamins & minerals like potassium, magnesium and phosphorous.<br/><br/>Our Moong Chilka is unpolished and pesticide-free. It can even be traced to its source of origin.<br/><br/>This pack comes to you from Surat and Bharuch districts of Gujarat. Be sure to get your Unpolished Moong Chilka Dal from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Moong Chilka Dal is available in 500gms and 1kg packs.</strong>'},
		{'name':'Unpolished Moong Dal','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0008_DeHaat_FOP_Unpolished_Moong_Dal_1kg_260722.webp','content':'Moong Dal is a natural source of protein and dietary fibre. It is rich in B vitamins & minerals like potassium, magnesium and phosphorous.<br/><br/>Our Moong Dal is unpolished and is pesticide-free. What’s more, it can even be traced to its source of origin.<br/><br/>This pack comes to you from Surat and Bharuch in Gujarat. Be sure to get your Unpolished Moong Dal from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Moong Dal is available in 500gms and 1kg packs.</strong>'},
		{'name':'Unpolished Kala Chana','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0009_DeHaat_FOP_Unpolished_Kala_Chana_1kg_260722.webp','content':'Kala Chana is a rich source of nutrients such as protein, fibre, and carbohydrates. It is high in vitamins like B6, C, folate, niacin, thiamine, riboflavin, and minerals including manganese, phosphorus, iron and copper. Because of its low starch content, it is very good for health.<br/><br/>Our Kala Chana is unpolished and pesticide-free. What’s more, it can be traced to its source of origin.<br/><br/>These packs come to you from Khargone and Dhar districts of Madhya Pradesh. Be sure to get your Kala Chana from DeHaat Honest Farms.<br/><br/>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br/><br/><strong>Our Unpolished Kala Chana is available in 500gms and 1kg packs.</strong>'},
		{'name':'Unpolished Kabuli Chana','img':'/static/assets/img/products/HONESR-FARMS-PRODUCTS_0010_DeHaat_FOP_Unpolished_Kabuli_Chana_1kg_260722.webp','content':'Kabuli Chana is a rich source of minerals such as manganese, magnesium, zinc, iron, copper, and vitamins such as thiamine and Vitamin B6.<br/><br/>Our Unpolished Kabuli Chana is of premium quality and big in size. It is unpolished, pesticide-free and can be traced to its source of origin.<br><br>These packs come to you from Khargone, Dhar and Bharwani districts of Madhya Pradesh. Be sure to get your Unpolished Kabuli Chana from DeHaat Honest Farms.<br><br>We make sure that you get honest food from crops that are grown in best conditions with the highest quality of raw materials. We carry out more than 230 quality checks to make sure the food stays pesticide-free and control the quality at every step right from procurement to processing.<br><br><strong>Our Unpolished Kabuli Chana is available in 500gms and 1kg packs.</strong>'}
	];

  return (
  	<>
      {myArray.map((prod,index) => (
      	<div
				  className="modal modal-fullscreen-xl"
				  id={`modal-fullscreen-xl${index+1}`}
				  tabIndex={-1}
				  role="dialog"
				  aria-hidden="true"
				  key="{index}"
				>
				  <div className="modal-dialog" role="document">
				    <div className="modal-content">
				      <div className="modal-header">
				      	<Link href="/">
				      		<div className="w-150px">
				        		<Image src={Logo} alt="honest-farm-logo"/>
				        	</div>
				        </Link>
				        <button
				          type="button"
				          className="close"
				          data-dismiss="modal"
				          aria-label="Close"
				        >
				          <span aria-hidden="true">×</span>
				        </button>
				      </div>
				      <div className="modal-body px-5">
				        <div className="row">
				          <div className="col-md-5 col-12">
				            <div className="container">
				              <div className="row">
				                <div className="col-md-12">
				                  <picture>
				                    <source srcSet={prod.img} type="image/webp" />
				                    <img className="d-flex mx-auto" src={prod.img} alt={prod.name} width="70%" />
				                  </picture>
				                </div>
				              </div>
				            </div>
				          </div>
				          <div className="col-md-7 col-12 px-0">
				            <div className="pt-3">
				              <h1 className="media-font-25" align="left">
				                {prod.name}
				              </h1>
				              <div
										  dangerouslySetInnerHTML={{
										    __html: prod.content
										  }}></div>
				            </div>
				          </div>
				        </div>
				      </div>
				    </div>
				  </div>
				</div>
      ))}
    </>
  )
}